// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: common/protobuf/sensor.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SensorReading struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	SensorType    string                 `protobuf:"bytes,2,opt,name=sensor_type,json=sensorType,proto3" json:"sensor_type,omitempty"` // fixed per A instance, but included for completeness
	Id1           string                 `protobuf:"bytes,3,opt,name=id1,proto3" json:"id1,omitempty"`                                 // uppercase A–Z
	Id2           int32                  `protobuf:"varint,4,opt,name=id2,proto3" json:"id2,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"` // Unix ms
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_common_protobuf_sensor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_sensor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_common_protobuf_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *SensorReading) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *SensorReading) GetSensorType() string {
	if x != nil {
		return x.SensorType
	}
	return ""
}

func (x *SensorReading) GetId1() string {
	if x != nil {
		return x.Id1
	}
	return ""
}

func (x *SensorReading) GetId2() int32 {
	if x != nil {
		return x.Id2
	}
	return 0
}

func (x *SensorReading) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_common_protobuf_sensor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_common_protobuf_sensor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_common_protobuf_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *StreamAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_common_protobuf_sensor_proto protoreflect.FileDescriptor

const file_common_protobuf_sensor_proto_rawDesc = "" +
	"\n" +
	"\x1ccommon/protobuf/sensor.proto\x12\x06sensor\"\x8d\x01\n" +
	"\rSensorReading\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x1f\n" +
	"\vsensor_type\x18\x02 \x01(\tR\n" +
	"sensorType\x12\x10\n" +
	"\x03id1\x18\x03 \x01(\tR\x03id1\x12\x10\n" +
	"\x03id2\x18\x04 \x01(\x05R\x03id2\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"#\n" +
	"\tStreamAck\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2K\n" +
	"\rIngestService\x12:\n" +
	"\x0eStreamReadings\x12\x15.sensor.SensorReading\x1a\x11.sensor.StreamAckB@Z>github.com/Yusufzhafir/worlder-team-assignment/common/protobufb\x06proto3"

var (
	file_common_protobuf_sensor_proto_rawDescOnce sync.Once
	file_common_protobuf_sensor_proto_rawDescData []byte
)

func file_common_protobuf_sensor_proto_rawDescGZIP() []byte {
	file_common_protobuf_sensor_proto_rawDescOnce.Do(func() {
		file_common_protobuf_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_protobuf_sensor_proto_rawDesc), len(file_common_protobuf_sensor_proto_rawDesc)))
	})
	return file_common_protobuf_sensor_proto_rawDescData
}

var file_common_protobuf_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_protobuf_sensor_proto_goTypes = []any{
	(*SensorReading)(nil), // 0: sensor.SensorReading
	(*StreamAck)(nil),     // 1: sensor.StreamAck
}
var file_common_protobuf_sensor_proto_depIdxs = []int32{
	0, // 0: sensor.IngestService.StreamReadings:input_type -> sensor.SensorReading
	1, // 1: sensor.IngestService.StreamReadings:output_type -> sensor.StreamAck
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_protobuf_sensor_proto_init() }
func file_common_protobuf_sensor_proto_init() {
	if File_common_protobuf_sensor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_protobuf_sensor_proto_rawDesc), len(file_common_protobuf_sensor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_protobuf_sensor_proto_goTypes,
		DependencyIndexes: file_common_protobuf_sensor_proto_depIdxs,
		MessageInfos:      file_common_protobuf_sensor_proto_msgTypes,
	}.Build()
	File_common_protobuf_sensor_proto = out.File
	file_common_protobuf_sensor_proto_goTypes = nil
	file_common_protobuf_sensor_proto_depIdxs = nil
}
